# Generated by Django 2.2.7 on 2019-12-12 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Has',
            new_name='Listing',
        ),
    ]
